entites := "entity/src/entities"

# Generate models
generate-models:
  sea-orm-cli generate entity -o {{ entites }} --with-serde both

# Seed the database from a City Ratings CSV files
seed:
  cd api && cargo run --example seeder

# Run the migrations
migrate:
  source .env && sea-orm-cli migrate up

# Initialize the API
init: migrate seed


