# Query all the cities.
GET http://localhost:8080/cities

###

# Query the city of Austin, TX.
GET http://localhost:8080/city/578c1427-d81f-4a9c-9292-0534fa40564b

###

# Retrieve all the city rating entries.
# Quite some data (460KB) to fetch, therefore a bit slow (~20s).
GET http://localhost:8080/ratings

###

# Retrieve the City Rating for Austin, TX.
GET http://localhost:8080/rating/578c1427-d81f-4a9c-9292-0534fa40564b

###

# Get fast city rating entries.
GET http://localhost:8080/fastratings

###

# Retrieve the SVG brochure for Austin, TX.
GET http://localhost:8080/brochure/578c1427-d81f-4a9c-9292-0534fa40564b

###

# Publish a new city analysis.
POST http://localhost:8080/task/analysis
Content-Type: application/json

{
  "id": "2b8a00ed-b6bd-49f9-98ef-ce97828ab9c1",
  "name": "bikeable_austin",
  "country": "country",
  "state": "state",
  "uuid": "8120e0a8-7821-427c-a52a-8b93adf5836e",
  "population": 1000,
  "ratings": 10,
  "created_at": "2022-07-10T02:39:45.122293+00:00",
  "updated_at": "2022-07-10T02:39:45.122293+00:00"
}
