# Format python files.
fmt-python:
    poetry run isort .
    poetry run black .

# Lint python files.
lint-python:
    poetry run isort --check .
    poetry run black --check .

# Build all figures
build:
    poetry run python figures/brochure_etl.py
    poetry run python figures/retrieve_etl.py
