[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
sea-orm = { workspace = true, features = [
  "debug-print",
  "runtime-tokio-native-tls",
  "sqlx-postgres",
] }
