[package]
name = "brochures"
version = "0.1.0"
edition = "2021"

[dependencies]
bnacore = { path = "../../bnacore" }
color-eyre = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["fmt"] }
walkdir = { workspace = true }
