default: fmt-md

# Meta task running all the linters at once.
lint: lint-md

# Lint markown files.
lint-md:
    npx --yes markdownlint-cli2 "**/*.md"

# Check spelling.
lint-spellcheck:
	npx --yes cspell --no-progress --show-suggestions --show-context "content/**/*.md"

# Meta tasks running all formatters at once.
fmt: fmt-md fmt-just

# Format the justfile.
fmt-just:
    just --fmt --unstable

# Format markdown files (default).
fmt-md:
    npx --yes prettier --write --prose-wrap always "content/**/*.md"
