use super::{CsvExt, ScorecardExt};
use crate::{Dataset, Error, PFB_S3_PUBLIC_DOCUMENTS, PFB_S3_STORAGE_BASE_URL};
use serde::Deserialize;
use url::Url;

/// Represent a PeopleForBikes city.
/// city,state,state_full,country,region,census_fips_code,census_latitude,census_longitude
#[derive(Debug, Deserialize, Clone)]
pub struct City23 {
    /// City name.
    pub city: String,
    /// Two letter code representing the state where the city is located.
    pub state: String,
    /// Full name of the state where the city is located.
    pub state_full: String,
    /// Country where the city is located.
    pub country: String,
    /// Region.`
    pub region: String,
    /// FIPS code.
    pub census_fips_code: u32,
    /// Latitude.
    pub census_latitude: f64,
    /// Longitude
    pub census_longitude: f64,
}

/// Represent the results from the BNA.
#[derive(Debug, Deserialize, Clone)]
pub struct BNA23 {
    /// Year of this analysis.
    pub year: u32,
    /// Population.
    pub census_population: u32,
    ///
    pub residential_speed_limit: u8,
    ///
    pub bna_id: String,
    /// BNA unique identifier.
    ///
    /// It is generated by a specific Bicyle Network Analysis (BNA) run and
    /// should be assimilated to a version number (each run will generate a
    /// new identifier).
    pub bna_uuid: String,
    ///
    pub bna_people: f64,
    ///
    pub bna_opportunity_employment: f64,
    ///
    pub bna_opportunity_k12_education: f64,
    ///
    pub bna_opportunity_technical_vocational_college: f64,
    ///
    pub bna_opportunity_higher_education: f64,
    ///
    pub bna_opportunity: f64,
    ///
    pub bna_core_services_doctors: f64,
    ///
    pub bna_core_services_dentists: f64,
    ///
    pub bna_core_services_hospitals: f64,
    ///
    pub bna_core_services_pharmacies: f64,
    ///
    pub bna_core_services_grocery: f64,
    ///
    pub bna_core_services_social_services: f64,
    ///
    pub bna_core_services: f64,
    ///
    pub bna_retail: f64,
    ///
    pub bna_recreation_parks: f64,
    ///
    pub bna_recreation_trails: f64,
    ///
    pub bna_recreation_community_centers: f64,
    ///
    pub bna_recreation: f64,
    ///
    pub bna_transit: f64,
    ///
    pub bna_overall_score: f64,
    ///
    pub bna_rounded_score: u8,
    ///
    pub bna_total_low_stress_miles: f64,
    ///
    pub bna_total_high_stress_miles: f64,
    ///
    pub pop_size: Size,
    ///
    pub rank: u32,
    ///
    pub rank_size: u32,
    ///
    pub rank_state: u32,
    ///
    pub rank_country: u32,
    ///
    pub rank_country_size: u32,
}

#[derive(Debug, Deserialize, Clone)]
#[serde(rename_all = "lowercase")]
pub enum Size {
    /// Represent small cities.
    Small,
    /// Represent medium cities.
    Medium,
    /// Represent large cities.
    Large,
}

#[derive(Debug, Deserialize, Clone)]
pub struct ScoreCard23 {
    /// City details.
    #[serde(flatten)]
    pub city: City23,
    /// BNA results.
    #[serde(flatten)]
    pub bna: BNA23,
}

impl CsvExt for ScoreCard23 {}

impl ScorecardExt for ScoreCard23 {
    /// Return the full name of the city.
    ///
    /// The full name has the following format: `{COUNTRY}-{STATE}-{CITY_NAME}`.
    fn full_name(&self) -> String {
        format!(
            "{}-{}-{}",
            self.city.country, self.city.state, self.city.city
        )
    }

    /// Return the URL of the specified dataset.
    fn url(&self, dataset: &Dataset) -> Result<Url, Error> {
        let mut dataset_url: String = String::new();
        if *dataset == Dataset::DataDictionary {
            dataset_url.push_str(PFB_S3_PUBLIC_DOCUMENTS);
        } else {
            dataset_url.push_str(PFB_S3_STORAGE_BASE_URL);
            dataset_url.push('/');
            dataset_url.push_str(&self.bna.bna_id);
        }
        dataset_url.push('/');
        dataset_url.push_str(&dataset.to_string());
        dataset_url.push('.');
        dataset_url.push_str(&dataset.extension());
        Ok(Url::parse(&dataset_url)?)
    }
}
