[package]
name = "spokes"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shortcodes"
path = "src/shortcodes.rs"

[[bin]]
name = "svggloo"
path = "src/svggloo.rs"

[dependencies]
bnacore = { path = "../bnacore" }
clap = { version = "3.2.17", features = ["cargo", "derive"] }
color-eyre = "0.6.2"
