name: pipelines/brochures

defaults:
  run:
    working-directory: pipelines/brochures

on:
  pull_request:
    paths:
      - ".github/workflows/pipelines-brochures.yml"
      - "pipelines/brochures/**"
      - "Cargo.toml"
    types:
      - opened
      - synchronize
      - reopened
  push:
    paths:
      - ".github/workflows/pipelines-brochures.yml"
      - "pipelines/brochures/**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
