//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::bna::Entity as Bna;
pub use super::city::Entity as City;
pub use super::community_survey::Entity as CommunitySurvey;
pub use super::infrastructure::Entity as Infrastructure;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
